### PR TITLE
Documentations for using sub-resource integrity, related to PR #7798

### PR DESCRIPTION
**Pull request by duboisp**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Can you please rebase?

**Comment by duboisp** [comment]
This was rebased from wet-boew/master as it was on last Saturday. Do you want me to rebase on your current branch?

**Comment by LaurentGoderre** [comment]
Yeah, it will make this cleaner. It will still merge ok upstream

**Comment by duboisp** [comment]
ok I will do

**Comment by duboisp** [comment]
rebase completed

**Pull request merged**
